<?php

namespace App\Libraries;

class Permissions
{
    static function permissions()
    {
        return [
            'Clients' => [
                'createClients' => 'Create Clients',
                'storeClients' => 'Store Clients',
                'clients' => 'View Clients',
                'editClients' => 'Edit Clients',
                'updateClients' => 'Update Clients',
                'deleteClients' => 'Delete Clients',
                // 'checkClientName' => 'Check Client Name'
            ],
            'Designation' => [
                'create_designation' => 'Create Designation',
                'storedesignation' => 'Store Designation',
                'designation' => 'View Designation',
                'edit_designation' => 'Edit Designation',
                'update_designation' => 'Update Designation',
                'deletedesignation' => 'Delete Designation',
            ],
            'Clients POC' => [
                'createClientPoc' => 'Create Client POC',
                'storeClientPoc' => 'Store Client POC',
                'ClientPoc' => 'View Clients POC',
                'editClientPoc' => 'Edit Client POC',
                'updateClientPoc' => 'Update Client POC',
                'deleteClientPoc' => 'Delete Client POC',
            ],
            // 'Company Profile' => [
            //     'createCompProfile' => 'Create Company Profile',
            //     'storeCompProfile' => 'Store Company Profile',
            //     'CompProfile' => 'View Company Profile',
            //     'editCompProfile' => 'Edit Company Profile',
            //     'updateCompProfile' => 'Update Company Profile',
            //     'deleteCompProfile' => 'Delete Company Profile',
            // ],
            'Schedule' => [
                'schedule' => 'Create Schedule',
                'schedule_store' => 'Store Schedule',
                'schedule_show' => 'View Schedule',
                'schedule_edit' => 'Edit Schedule',
                'schedule_update' => 'Update Schedule',
                'schedule_delete' => 'Delete Schedule',
            ],
            'Funnel' => [
                'createFunnel' => 'Create Funnel',
                'storeFunnel' => 'Store Funnel',
                'funnel' => 'View Funnel',
                'editFunnel' => 'Edit Funnel',
                'updateFunnel' => 'Update Funnel',
                'deleteFunnel' => 'Delete Funnel',
            ],
            'Quotation' => [
                'create_quotation' => 'Create Quotation',
                'store_quotation' => 'Store Quotation',
                'quotations' => 'View Quotation',
                'versionInvoice' => 'Create Quotation Version',
                'store_version' => 'Store Quotation Version',
                // 'view_invoice' => 'View Quotation',
                'view_expiry_days' => 'Quotations Expiry',
                'deleteInvoice' => 'Delete Quotations',
                'approval_quotations' => 'Expiry Approvals Quotations',
                'view_expiry_approvals' => 'View Expiry Approvals Quotations',
            ],
            'Order' => [
                'createOrder' => 'Create Order',
                'storeOrder' => 'Store Order',
                'order' => 'View Order',
                'editOrder' => 'Edit Order',
                'updateOrder' => 'Update Order',
                'deleteOrder' => 'Delete Order',
                'get_purposal' => 'Get Purposal',
                'purposal_lists' => 'Purposal Lists',
                'get_product_list' => 'Get Product List',
                'checkQuery' => 'Check Query',
            ],
            'Business Category' => [
                'businessCategory' => 'Create Business Category',
                'store_businessCategory' => 'Store Business Category',
                'view_businessCategory' => 'View Business Category',
                'edit_businessCategory' => 'Edit Business Category',
                'update_businessCategory' => 'Update Business Category',
                'delete_businessCategory' => 'Delete Business Category',
            ],
            'Region' => [
                'region' => 'Create Region',
                'storeRegion' => 'Store Region',
                'viewRegion' => 'View Region',
                'editRegion' => 'Edit Region',
                'updateRegion' => 'Update Region',
                'deleteRegion' => 'Delete Region',
            ],
            'Area' => [
                'area' => 'Create Area',
                'storeArea' => 'Store Area',
                'viewArea' => 'View Area',
                'editArea' => 'Edit Area',
                'updateArea' => 'Update Area',
                'deleteArea' => 'Delete Area',
            ],
            'Sector' => [
                'sector' => 'Create Sector',
                'storeSector' => 'Store Sector',
                'viewSector' => 'View Sector',
                'editSector' => 'Edit Sector',
                'updateSector' => 'Update Sector',
                'deleteSector' => 'Delete Sector',
            ],
            'Town' => [
                'createTown' => 'Create Town',
                'storeTown' => 'Store Town',
                'town' => 'View Town',
                'editTown' => 'Edit Town',
                'updateTown' => 'Update Town',
                'deleteTown' => 'Delete Town',
            ],
            'Visit Type' => [
                'visitTypeCreate' => 'Create Visit Type',
                'visitTypeStore' => 'Store Visit Type',
                'visitTypeView' => 'View Visit Type',
                'visitTypeEdit' => 'Edit Visit Type',
                'visitTypeUpdate' => 'Update Visit Type',
                'visitTypeDelete' => 'Delete Visit Type',
            ],
            'Main Unit' => [
                'mainUnitCreate' => 'Create Main Unit',
                'mainUnitStore' => 'Store Main Unit',
                'mainUnit' => 'View Main Unit',
                'mainUnitEdit' => 'Edit Main Unit',
                'mainUnitUpdate' => 'Update Main Unit',
                'mainUnitDelete' => 'Delete Main Unit',
            ],
            'UOM' => [
                'uomCreate' => 'Create UOM',
                'uomStore' => 'Store UOM',
                'uom' => 'View UOM',
                'uomEdit' => 'Edit UOM',
                'uomUpdate' => 'Update UOM',
                'uomDelete' => 'Delete UOM',
            ],
            'Product Group' => [
                'createProductGroup' => 'Create Product Group',
                'productGroupStore' => 'Store Product Group',
                'productGroup' => 'View Product Group',
                'productGroupEdit' => 'Edit Product Group',
                'productGroupUpdate' => 'Update Product Group',
                'productGroupDelete' => 'Delete Product Group',
            ],
            'Product Category' => [
                'createCategory' => 'Create Product Category',
                'storeCategory' => 'Store Product Category',
                'category' => 'View Product Category',
                'editCategory' => 'Edit Product Category',
                'updateCategory' => 'Update Product Category',
                'deleteCategory' => 'Delete Product Category',
            ],
            'Product' => [
                'createProduct' => 'Create Product',
                'storeProduct' => 'Store Product',
                'product' => 'View Product',
                'editProduct' => 'Edit Product',
                'updateProduct' => 'Update Product',
                'deleteProduct' => 'Delete Product',
            ],
            'Single Product Price' => [
                'productPriceCreate' => 'Create Product Price',
                'productPriceStore' => 'Store Product Price',
                'productPrice' => 'View Product Price',
                'productPriceEdit' => 'Edit Product Price',
                'productPriceUpdate' => 'Update Product Price',
                'productPriceDelete' => 'Delete Product Price',
            ],
            'Group Wise Product Price' => [
                'product_price_update' => 'Update Group Wise Product Price',
                'update_product_price' => 'Update Product Price',
            ],
            'Term And Condition' => [
                'TandC' => 'Create Term And Condition',
                'storeTandC' => 'Store Term And Condition',
                'viewTandC' => 'View Term And Condition',
                'edit_tandc' => 'Edit Term And Condition',
                'update_tandc' => 'Edit Term And Condition',
                'deleteTandC' => 'Delete Term And Condition',
            ],
            'Target' => [
                'createTarget' => 'Create Target',
                'storeTask' => 'Store Target',
                // 'fetch_users' => 'Fetch Users',
            ],
            // 'Status' => [
            //     'createStatus' => 'Create Status',
            //     'storeStatus' => 'Store Status',
            //     'status' => 'View Status',
            //     'editStatus' => 'Edit Status',
            //     'updateStatus' => 'Update Status',
            //     'deleteStatus' => 'Delete Status',
            // ],
            'Group' => [
                'createGroup' => 'Create Group',
                'storeGroup' => 'Edit Group',
                'group' => 'View Group',
                'editGroup' => 'Edit Group',
                'updateGroup' => 'Update Group',
                'deleteGroup' => 'Delete User',
            ],
            'User' => [
                'createuser' => 'Create User',
                'storeuser' => 'Edit User',
                'user' => 'View User',
                'edituser' => 'Edit User',
                'updateuser' => 'Update User',
                'deleteuser' => 'Delete User',
            ],
            'User Profile' => [
                'editProfile' => 'Edit Profile',
                'updateProfile' => 'Update Profile',
                // 'changeStatus' => 'Change Status',
                // 'checkEmail' => 'Check Email',
                // 'checkUser' => 'Check User',
            ],
            'Password' => [
                'change-password' => 'Change Password',
                'change_password' => 'Store Password',
            ],
            'Modular_group' => [
                'create_modular_group' => 'Create Modular_group',
                'store_modular_group' => 'Store Modular_group',
                'modular_group' => 'View Modular_group',
                'edit_modular_group' => 'Edit Modular_group',
                'update_modular_group' => 'Update Modular_group',
                'delete_modular_group' => 'Delete Modular_group',
            ],
            // 'User Role' => [
            //     'user_role_create' => 'Create User Role',
            //     'user_role' => 'View User Role',
            //     'user_role_edit' => 'Edit User Role',
            //     'user_role_delete' => 'Delete User Role',
            // ],
            'Business Profile' => [
                'businessProfile' => 'Create Business Profile',
                'updateBusinessProfile' => 'Update Business Profile',
            ],
            'Reports' => [
                'scheduleReports' => 'View Schedule Reports',
                'funnelReports' => 'View Funnel Reports',
                'purposalReports' => 'View Quotation Reports',
                'orderReports' => 'View Order Reports',
                'all_work' => 'View All Work Reports',
                'completed_work' => 'View Completed Work Reports',
            ],
            'Reminder' => [
                'scheduleReminder' => 'View Schedule Reminders',
                'funnelReminder' => 'View Funnel Reminders',
                'purposalReminder' => 'View Quotation Reminders',
                'orderReminder' => 'View Order Reminders',
                'delete_schedule_reminder' => 'Delete Schedule Reminders',
                'delete_funnel_reminder' => 'Delete Funnel Reminders',
                'delete_invoice_reminder' => 'Delete Quotation Reminders',
                'delete_order_reminder' => 'Delete Order Reminders',
            ],
            'Remarks' => [
                'scheduleRemarks' => 'View Schedule Remarks',
                'funnelRemarks' => 'View Funnel Remarks',
                'purposalRemarks' => 'View Quotation Remarks',
                'orderRemarks' => 'View Order Remarks',
                'all_remarks' => 'View All Remarks',
            ],
        ];
    }
}
